/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_onirec_PclzfWriter */

#ifndef _Included_org_pointclouds_onirec_PclzfWriter
#define _Included_org_pointclouds_onirec_PclzfWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pointclouds_onirec_PclzfWriter
 * Method:    compress
 * Signature: (IJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_pointclouds_onirec_PclzfWriter_compress
  (JNIEnv *, jclass, jint, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
