/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_onirec_PclzfWriter */

#ifndef _Included_org_pointclouds_onirec_PclzfWriter
#define _Included_org_pointclouds_onirec_PclzfWriter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_pointclouds_onirec_PclzfWriter_PCLZF_HEADER_LENGTH
#define org_pointclouds_onirec_PclzfWriter_PCLZF_HEADER_LENGTH 37L
/*
 * Class:     org_pointclouds_onirec_PclzfWriter
 * Method:    compress
 * Signature: (IJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_pointclouds_onirec_PclzfWriter_compress
  (JNIEnv *, jclass, jint, jlong, jbyteArray);

/*
 * Class:     org_pointclouds_onirec_PclzfWriter
 * Method:    deinterleaveRGB
 * Signature: (IIJJ)V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_onirec_PclzfWriter_deinterleaveRGB
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
